[tool.poetry]
name = "lk-qtquick-scaffold"
version = "1.3.0.dev1"
homepage = "https://github.com/likianta/lk-qtquick-scaffold"
description = "A flexible toolset to improve QML coding experience for PyQt/PySide development."
readme = "README.md"
authors = ["Likianta <likianta@foxmail.com>"]
license = "MIT"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.8"
lk-lambdex = ""
lk-logger = ""
lk-utils = ""
qtpy = ""

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
